[tox]
env_list = lint, unit
[testenv]
runner = uv-venv-lock-runner
package = skip
[testenv:lint]
dependency_groups = lint
commands =
    ruff check src tests
    ruff format --check src tests
[testenv:unit]
dependency_groups = unit
commands = pytest tests/unit --cov=src {posargs}
[testenv:integration]
dependency_groups = integration
passenv = OCTEZ_*, JUJU_DATA
commands = pytest tests/integration {posargs}

[testenv:format]
dependency_groups = lint
commands = ruff format src tests
